#paths:
#  files: /2kdata/dev/289_europeana/websites/europeana_files
extensions:
  - Bolt\Extension\Europeana\ViewBlocks\ViewBlocksExtension
  - Bolt\Extension\Europeana\ZohoImport\ZohoImportExtension
  - Bolt\Extension\Europeana\SelectAsync\SelectAsyncExtension
  - Bolt\Extension\TwoKings\FeaturedItems\FeaturedItemsExtension
  - Bolt\Extension\TwoKings\Oembed\OembedExtension
