main:
    -
        label: 'About us '
        path: /page/105
        submenu:
            -
                label: 'Mission '
                path: page/2
            -
                label: 'Services and Tools'
                path: page/728
            -
                label: Projects
                path: page/493
            -
                label: Partnerships
                path: page/750
            -
                label: Events
                path: page/476
            -
                label: Foundation
                path: page/85
            -
                path: page/455
                label: Staff
            -
                path: page/8
                label: Careers
    -
        path: /page/4
        label: 'Join the Network '
        submenu:
            -
                label: 'Join us!'
                path: page/153
            -
                label: Communities
                path: page/19
            -
                label: 'Members '
                path: page/443
            -
                label: 'Members Council'
                path: page/86
            -
                path: page/440
                label: 'Management Board'
            -
                path: page/20
                label: 'Task Forces and Working Groups'
            -
                label: Documentation
                path: page/463
    -
        label: 'Share your data '
        path: /page/722
        submenu:
            -
                label: Process
                path: page/723
            -
                label: Metadata
                path: page/724
            -
                path: page/725
                label: Copyright
            -
                label: Media
                path: page/726
            -
                path: page/727
                label: Enrichment
secondary: {  }
footer:
    -
        label: News
        path: /page/news
    -
        label: Events
        link: /page/events
    -
        label: Publications
        path: page/35
    -
        label: 'Contact us'
        path: /about-us/office-employees
    -
        label: 'Terms & policies'
        link: 'http://europeana.eu/portal/rights/terms-and-policies.html'