.base: &base
    hostname: guust
    user: lodewijk
    application: deploytest
    deploy_path: /2kdata/dev/____users/lodewijk/deploytest
    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: europeana_cope
    git_tty: true
    keep_releases: 10
    cleanup_use_sudo: true
    snapshots_dir: snapshots
    shared_files:
      - '.bolt.yml'
    keep_files:
      - 'app/config/menu.yml'
      - 'app/config/taxonomy.yml'
      - 'app/config/extensions/zohoimport.europeana_local.yml'
      - 'extensions/bundles/europeana/zohoimport/TokenStorage/zcrm_oauthtokens.txt'
    writable_dirs:
      - 'app/config'
      - 'app/config/extensions'
      - 'app/database'
      - 'extensions'
      - 'public'
      - 'public/bolt-public'
      - 'extensions/bundles/europeana/zohoimport/TokenStorage'
      - 'vendor/zohocrm/php-sdk/src/oauth/utility'
    allow_anonymous_stats: false
    default_timeout: 10000

cope.lodewijk.twokings.eu:
    <<: *base
    hostname: kwabbernoot/development
    stage: development
    default_branch: development
    application: cope
    keep_releases: 3
    deploy_path: /raiddata/lodewijk/cope
    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
    thumb_files_path: /raiddata/lodewijk/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: 192.168.3.9
    mysql_db: lodewijk_europeana_pro

cope.twokings.eu:
    <<: *base
    hostname: kwabbernoot/test
    stage: test
    application: cope
    keep_releases: 3
    deploy_path: /raiddata/www/cope
    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
    thumb_files_path: /raiddata/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: 192.168.3.9
    mysql_db: lodewijk_europeana_pro

#cope.twokings.eu:
#    <<: *base
#    hostname: twokings.eu
#    stage: test
#    application: cope
#    keep_releases: 3
#    deploy_path: /2kdata/dev/289_europeana/websites/copedeploy
#    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
#    thumb_files_path: /2kdata/dev/289_europeana/websites/copedeploy/shared/thumbs
#    repository: git@github.com:europeana/EuropeanaCopeBolt.git
#    mysql_host: localhost
#    mysql_db: europeana_cope

pro-beta.europeana.eu:
    <<: *base
#    hostname: cope-test.eanadev.org
    hostname: pro-beta.europeana.eu
    user: deploy
    stage: accept
    default_branch: release
    application: cope
    keep_releases: 10
    deploy_path: /var/www/cope
    shared_files_path: "/home/dropbox/Dropbox\\ \\(Europeana\\ Pro\\)"
    thumb_files_path: /var/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: copedb

pro.europeana.eu:
    <<: *base
    hostname: pro.europeana.eu
    user: deploy
    stage: production
    default_branch: release
    application: cope
    keep_releases: 10
    deploy_path: /var/www/cope
    shared_files_path: "/home/dropbox/Dropbox\\ \\(Europeana\\ Pro\\)"
    thumb_files_path: /var/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: copedb
